open Lang

let s_ez_timeline = ss_ "ezTimeline"
let s_nav_home = ss_ "homeNav"
let s_home_title = ss_ "homeTitle"
let s_home_subtitle = ss_ "homeSubtitle"
let s_create_timeline_title = ss_ "createTimelineTitle"
let s_create_timeline_descr = ss_ "createTimelineDescr"
let s_create_timeline_name_help  = ss_ "createTimelineNameHelp"
let s_create_timeline_descr_help  = ss_ "createTimelineDescrHelp"
let s_create_timeline_button = ss_ "createTimelineButton"

let s_share_title = ss_ "shareTitle"
let s_share_descr = ss_ "shareDescr"
let s_share_help = ss_ "shareHelp"

let s_ponderation_help = ss_ "ponderationHelp"
let s_edit_element_help = ss_ "editElementHelp"
let s_add_element_help = ss_ "addElementHelp"
let s_filter_help = ss_ "filterHelp"

let s_name = ss_ "name"
let s_events = ss_ "events"
let s_description = ss_ "description"
let s_share = ss_ "share"
let s_categories = ss_ "categories"
let s_extra_filters = ss_ "extraFilters"
let s_filter = ss_ "filter"
let s_min_ponderation = ss_ "minimalPonderation"
let s_max_ponderation = ss_ "maximalPonderation"
let s_from = ss_ "from"
let s_to = ss_ "to"
let s_media = ss_ "media"
let s_headline = ss_ "headline"
let s_unique_id = ss_ "uniqueId"
let s_category = ss_ "category"
let s_tags = ss_ "tags"
let s_ponderation = ss_ "ponderation"
let s_confidential = ss_ "confidential"
let s_back = ss_ "back"
let s_remove_event = ss_ "removeEvent"
let s_add_new_event = ss_ "addNewEvent"
let s_edit_event = ss_ "editEvent"
let s_export_help = ss_ "exportHelp"

let s_default_title = ss_ "defaultTimelineTitle"

let s_alert_edition_conflict = ss_ "alertEditionConflict"
let s_alert_edition_failed = ss_ "alertEditionFailed"
let s_alert_no_view_token = ss_ "alertNoViewToken"
let s_alert_error_view_token = ss_ "alertErrorViewToken"
let s_alert_no_timeline_selected = ss_ "alertNoTimelineSelected"
let s_alert_unknown_event = ss_ "alertUnknownEvent"
let s_alert_title_deletion = ss_ "alertTitleDeletion"
let s_alert_timeline_creation = ss_ "alertTimelineCreation"

let s_confirm_remove_event = ss_ "confirmRemoveEvent"
